// Auto-generated by build_data.py — EF 3.1 CF matrix + BOM for the
// SOLARA LCA engine (Impact = Σ Q × CF). CFs are screening-grade, back-
// derived to reproduce the Farm32 study golden record exactly.
window.LCA_DATA = {
  "method": "Environmental Footprint 3.1 (adapted) V1.04",
  "tool_source": "SimaPro 10.3 / Farm32 study (WUR 2026)",
  "categories": [
    {
      "key": "climate",
      "label": "Climate change",
      "unit": "kg CO₂ eq",
      "golden": {
        "indoor": 2.3758167,
        "openfield": 7.0311717
      }
    },
    {
      "key": "fossils",
      "label": "Resource use, fossils",
      "unit": "MJ",
      "golden": {
        "indoor": 27.653139,
        "openfield": 90.105003
      }
    },
    {
      "key": "water",
      "label": "Water use",
      "unit": "m³ depriv.",
      "golden": {
        "indoor": 1.1425808,
        "openfield": 6.5789182
      }
    },
    {
      "key": "land",
      "label": "Land use",
      "unit": "Pt",
      "golden": {
        "indoor": 126.30825,
        "openfield": 13.045455
      }
    },
    {
      "key": "acid",
      "label": "Acidification",
      "unit": "mol H⁺ eq",
      "golden": {
        "indoor": 0.012026403,
        "openfield": 0.032717615
      }
    },
    {
      "key": "eutroM",
      "label": "Eutrophication, marine",
      "unit": "kg N eq",
      "golden": {
        "indoor": 0.0023717689,
        "openfield": 0.011215369
      }
    },
    {
      "key": "eutroF",
      "label": "Eutrophication, freshwater",
      "unit": "kg P eq",
      "golden": {
        "indoor": 0.00072264779,
        "openfield": 0.00063618874
      }
    },
    {
      "key": "eutroT",
      "label": "Eutrophication, terrestrial",
      "unit": "mol N eq",
      "golden": {
        "indoor": 0.028222529,
        "openfield": 0.12974266
      }
    },
    {
      "key": "ecotox",
      "label": "Ecotoxicity, freshwater",
      "unit": "CTUe",
      "golden": {
        "indoor": 13.229216,
        "openfield": 20.55772
      }
    },
    {
      "key": "pm",
      "label": "Particulate matter",
      "unit": "disease inc.",
      "golden": {
        "indoor": 1.45426e-07,
        "openfield": 1.37703e-07
      }
    },
    {
      "key": "ozone",
      "label": "Ozone depletion",
      "unit": "kg CFC11 eq",
      "golden": {
        "indoor": 1.29812e-07,
        "openfield": 1.92703e-07
      }
    },
    {
      "key": "photo",
      "label": "Photochemical ozone formation",
      "unit": "kg NMVOC eq",
      "golden": {
        "indoor": 0.0086261827,
        "openfield": 0.039058672
      }
    },
    {
      "key": "ion",
      "label": "Ionising radiation",
      "unit": "kBq U-235 eq",
      "golden": {
        "indoor": 0.10224601,
        "openfield": 0.047561603
      }
    },
    {
      "key": "htc",
      "label": "Human toxicity, cancer",
      "unit": "CTUh",
      "golden": {
        "indoor": 9.2342481e-10,
        "openfield": 1.0753847e-09
      }
    },
    {
      "key": "htnc",
      "label": "Human toxicity, non-cancer",
      "unit": "CTUh",
      "golden": {
        "indoor": 5.5699e-08,
        "openfield": 7.4082e-08
      }
    },
    {
      "key": "minmet",
      "label": "Resource use, minerals & metals",
      "unit": "kg Sb eq",
      "golden": {
        "indoor": 4.9067289e-05,
        "openfield": 1.8238733e-05
      }
    }
  ],
  "flows": [
    {
      "id": "elec_pv",
      "label": "Electricity, PV + battery (LED+HVAC)",
      "unit": "kWh",
      "group": "Energy",
      "q": {
        "indoor": 26.44,
        "openfield": 0.0
      }
    },
    {
      "id": "elec_grid",
      "label": "Electricity, grid (pumps/controls)",
      "unit": "kWh",
      "group": "Energy",
      "q": {
        "indoor": 0.0,
        "openfield": 0.80052
      }
    },
    {
      "id": "diesel",
      "label": "Diesel, irrigation pump",
      "unit": "kg",
      "group": "Energy",
      "q": {
        "indoor": 0.0,
        "openfield": 0.16201
      }
    },
    {
      "id": "co2",
      "label": "CO₂ enrichment (liquid)",
      "unit": "kg",
      "group": "Inputs",
      "q": {
        "indoor": 0.532,
        "openfield": 0.0
      }
    },
    {
      "id": "water_in",
      "label": "Water (RO make-up / borehole drip)",
      "unit": "kg",
      "group": "Water",
      "q": {
        "indoor": 3.41145,
        "openfield": 321.3748379
      }
    },
    {
      "id": "npk",
      "label": "NPK fertiliser (A+B, all stages)",
      "unit": "kg",
      "group": "Inputs",
      "q": {
        "indoor": 0.01362,
        "openfield": 0.17154
      }
    },
    {
      "id": "pest",
      "label": "Plant protection (a.i.)",
      "unit": "kg ai",
      "group": "Inputs",
      "q": {
        "indoor": 0.0,
        "openfield": 0.0041932
      }
    },
    {
      "id": "substrate",
      "label": "Propagation substrate (foam/peat)",
      "unit": "kg",
      "group": "Inputs",
      "q": {
        "indoor": 0.00825,
        "openfield": 0.022872
      }
    },
    {
      "id": "naocl",
      "label": "Sodium hypochlorite (sterilise)",
      "unit": "kg",
      "group": "Inputs",
      "q": {
        "indoor": 7.766e-05,
        "openfield": 0.0
      }
    }
  ],
  "cf": {
    "indoor": {
      "climate": {
        "elec_pv": 0.041334178593040845,
        "co2": 0.9824805902255639,
        "npk": 24.421023348017627,
        "substrate": 28.797778181818185,
        "water_in": 0.03482121531899926,
        "naocl": 917.7762168426475
      },
      "fossils": {
        "elec_pv": 0.575235493570348,
        "co2": 7.796937687969924,
        "npk": 263.94332378854625,
        "substrate": 335.18956363636363,
        "water_in": 0.3242391241261047,
        "naocl": 10682.386943085243
      },
      "water": {
        "water_in": 0.16746263319116506,
        "elec_pv": 0.012964229954614218,
        "co2": 0.1718166616541353,
        "npk": 5.872294860499267,
        "substrate": 4.154839272727272,
        "naocl": 294.25207313932526
      },
      "land": {
        "elec_pv": 3.726188918305598,
        "substrate": 1531.0090909090911,
        "npk": 556.4240088105727,
        "co2": 9.496860902255639,
        "water_in": 0.37024798839203277,
        "naocl": 16264.260880762298
      },
      "acid": {
        "elec_pv": 0.00018194255673222392,
        "npk": 0.264898744493392,
        "co2": 0.0027127224812030074,
        "substrate": 0.14577458181818184,
        "water_in": 0.00017626526843424352,
        "naocl": 4.645790497038372
      },
      "eutroM": {
        "npk": 0.09577627716593247,
        "elec_pv": 1.7940763237518912e-05,
        "substrate": 0.034498456727272725,
        "co2": 0.00031207485526315795,
        "water_in": 2.780951091178238e-05,
        "naocl": 0.6108083698171517
      },
      "eutroF": {
        "npk": 0.023876028303964757,
        "elec_pv": 7.652851028744327e-06,
        "substrate": 0.01051124058181818,
        "co2": 0.00010866884060150375,
        "water_in": 1.0591504931920446e-05,
        "naocl": 0.18610553438063354
      },
      "eutroT": {
        "npk": 1.0360693465491924,
        "elec_pv": 0.00023483193570347956,
        "co2": 0.0063659839849624054,
        "substrate": 0.3420912606060606,
        "water_in": 0.0003309153468466488,
        "naocl": 7.268227916559362
      },
      "ecotox": {
        "npk": 339.9578267254038,
        "elec_pv": 0.15010456883509832,
        "substrate": 240.53119999999998,
        "co2": 2.486694736842105,
        "water_in": 0.2326731917513081,
        "naocl": 6813.915014164306
      },
      "pm": {
        "elec_pv": 2.6401089258698937e-09,
        "npk": 2.3490249632892803e-06,
        "co2": 3.280285714285713e-08,
        "substrate": 1.7627393939393938e-06,
        "water_in": 2.1314397103870787e-09,
        "naocl": 5.617795518928663e-05
      },
      "ozone": {
        "npk": 3.8123935389133626e-06,
        "elec_pv": 1.4729046898638425e-09,
        "co2": 3.416105263157895e-08,
        "substrate": 1.5734787878787879e-06,
        "water_in": 1.522074191326269e-09,
        "naocl": 3.3430852433685295e-05
      },
      "photo": {
        "elec_pv": 0.00013702710794251134,
        "npk": 0.1646701543318649,
        "co2": 0.002270048078947369,
        "substrate": 0.10455979030303031,
        "water_in": 0.0001264298568057571,
        "naocl": 3.33228793458666
      },
      "ion": {
        "elec_pv": 0.002706966981845688,
        "co2": 0.019219174812030074,
        "npk": 0.750704919236417,
        "substrate": 0.7436073454545454,
        "water_in": 0.000899142681264565,
        "naocl": 13.165852433685295
      },
      "htc": {
        "elec_pv": 1.397011815431165e-11,
        "npk": 1.694979460352423e-08,
        "substrate": 1.6789541999999996e-08,
        "co2": 2.0829131052631577e-10,
        "water_in": 1.3534198214835335e-11,
        "naocl": 3.5671831444759207e-07
      },
      "htnc": {
        "npk": 1.5540102790014685e-06,
        "elec_pv": 6.319856278366111e-10,
        "substrate": 1.0127090909090908e-06,
        "co2": 1.0469736842105264e-08,
        "water_in": 8.163537498717556e-10,
        "naocl": 1.4344321400978626e-05
      },
      "minmet": {
        "elec_pv": 1.1505945226928895e-06,
        "npk": 0.0005043627356828194,
        "substrate": 0.0007137060218181817,
        "co2": 6.456222236842106e-06,
        "water_in": 4.314935496636328e-07,
        "naocl": 0.01263643806335308
      }
    },
    "openfield": {
      "climate": {
        "diesel": 14.755869254984262,
        "elec_grid": 1.5809859916054563,
        "npk": 12.296557712486882,
        "water_in": 0.001750273106866653,
        "pest": 100.60819946580176,
        "substrate": 12.296557712486884
      },
      "fossils": {
        "diesel": 250.27622585025614,
        "elec_grid": 22.51161819817119,
        "npk": 105.05421825813222,
        "water_in": 0.022429883705590504,
        "pest": 859.5345130210817,
        "substrate": 118.18599554039874
      },
      "water": {
        "water_in": 0.014739240741286422,
        "npk": 4.602251276670165,
        "diesel": 3.248647960002469,
        "elec_grid": 0.41091529255983616,
        "pest": 31.378985977296576,
        "substrate": 2.876407047918853
      },
      "land": {
        "npk": 30.419622245540403,
        "substrate": 142.59197927597063,
        "diesel": 12.078379421023394,
        "water_in": 0.004059264591230775,
        "elec_grid": 0.9777735721780842,
        "pest": 124.44390918630162
      },
      "acid": {
        "npk": 0.08010608779293459,
        "diesel": 0.056545473736189136,
        "elec_grid": 0.004904454354669464,
        "water_in": 8.144412353821058e-06,
        "pest": 0.4681524611275398,
        "substrate": 0.05721863413781042
      },
      "eutroM": {
        "npk": 0.037920683339162875,
        "diesel": 0.009691695944694772,
        "water_in": 4.187771167134052e-06,
        "elec_grid": 0.0011208083745565382,
        "pest": 0.13373281741867785,
        "substrate": 0.014710609916054563
      },
      "eutroF": {
        "npk": 0.0014834761338463334,
        "water_in": 4.355086531184836e-07,
        "diesel": 0.0006282957743349177,
        "elec_grid": 9.536632289012141e-05,
        "pest": 0.009103149003147952,
        "substrate": 0.0011126071003847498
      },
      "eutroT": {
        "npk": 0.3781702809840271,
        "diesel": 0.1761828603172644,
        "pest": 3.0941204807784035,
        "water_in": 3.229690559417627e-05,
        "elec_grid": 0.00972437865387498,
        "substrate": 0.22690216859041626
      },
      "ecotox": {
        "pest": 1961.053133644949,
        "npk": 33.55579806459135,
        "diesel": 17.76483426948954,
        "water_in": 0.00639680447116921,
        "elec_grid": 1.2840228851246691,
        "substrate": 26.964480587618045
      },
      "pm": {
        "diesel": 3.229870995617555e-07,
        "npk": 2.2476880027981814e-07,
        "elec_grid": 2.4082371458551943e-08,
        "water_in": 4.28480962914863e-11,
        "pest": 1.970375846608795e-06,
        "substrate": 2.408237145855194e-07
      },
      "ozone": {
        "npk": 4.7181566981462045e-07,
        "diesel": 3.092573297944572e-07,
        "elec_grid": 3.37011192724729e-08,
        "water_in": 4.796965468963369e-11,
        "pest": 2.757364304111418e-06,
        "substrate": 3.3701119272472897e-07
      },
      "photo": {
        "diesel": 0.096435212641195,
        "npk": 0.05920050553806693,
        "elec_grid": 0.0068308275620846464,
        "water_in": 9.722894861396368e-06,
        "pest": 0.7451811885910522,
        "substrate": 0.06830827562084646
      },
      "ion": {
        "elec_grid": 0.029706692524858844,
        "npk": 0.05545249271306984,
        "diesel": 0.04110008283439295,
        "water_in": 1.1839533750878014e-05,
        "pest": 0.5671277663836688,
        "substrate": 0.06238405430220357
      },
      "htc": {
        "npk": 2.131460872099802e-09,
        "pest": 6.155020700181245e-08,
        "diesel": 1.194798135917536e-09,
        "elec_grid": 1.61202923099985e-10,
        "water_in": 2.6769605412222596e-13,
        "substrate": 1.880700769499825e-09
      },
      "htnc": {
        "pest": 6.00683964513975e-06,
        "npk": 1.2955928646379854e-07,
        "diesel": 7.316289117955683e-08,
        "elec_grid": 9.254234747414181e-09,
        "water_in": 1.6136110822757108e-11,
        "substrate": 9.71694648478489e-08
      },
      "minmet": {
        "npk": 4.040292957910691e-05,
        "diesel": 2.4767120918461823e-05,
        "elec_grid": 4.101049242992054e-06,
        "substrate": 9.569114900314793e-05,
        "water_in": 3.4051327327017218e-09,
        "pest": 0.0001739839072784508
      }
    }
  },
  "single_score": {
    "indoor": 0.0012460829,
    "openfield": 0.00056099551
  },
  "stages": [
    {
      "key": "LCS1",
      "label": "Raw materials",
      "desc": "Seed, growing media, water, fertiliser stocks, and the amortised share of the building, solar plant and equipment."
    },
    {
      "key": "LCS2",
      "label": "Cultivation",
      "desc": "Growing the crop: lighting, climate control, CO₂, nutrients, water. The factory floor."
    },
    {
      "key": "LCS3",
      "label": "Post-harvest",
      "desc": "Wash, cool, sleeve and short cold-store before dispatch."
    },
    {
      "key": "LCS4",
      "label": "Distribution",
      "desc": "Getting it to Europe: refrigerated road, sea ferry, inland trucking and the DC-to-store leg."
    },
    {
      "key": "LCS5",
      "label": "Packaging",
      "desc": "The sleeve, label, carton, pallet and stretch wrap."
    },
    {
      "key": "LCS6",
      "label": "Retail",
      "desc": "Supermarket refrigeration and the basil lost on-shelf."
    },
    {
      "key": "LCS7",
      "label": "Use",
      "desc": "The shopper's trip home, the home fridge, and inedible stems."
    },
    {
      "key": "LCS8",
      "label": "End of life",
      "desc": "Recycling, incineration, landfill and composting of waste."
    }
  ],
  "stage_climate": {
    "indoor": {
      "LCS1": 0.13125,
      "LCS2": 1.4647,
      "LCS3": 0.00401,
      "LCS4": 0.63299,
      "LCS5": 0.03596,
      "LCS6": 0.05728,
      "LCS7": 0.00484,
      "LCS8": 0.04479
    },
    "openfield": {
      "LCS1": 0.40793,
      "LCS2": 2.01014,
      "LCS3": 0.04495,
      "LCS4": 4.24734,
      "LCS5": 0.08074,
      "LCS6": 0.12862,
      "LCS7": 0.01088,
      "LCS8": 0.10058
    }
  },
  "business": {
    "headline": "Can solar-powered indoor farming in Morocco beat air-freighted basil from Kenya?",
    "question": "Farm32 is a pre-operational plan: a sealed, climate-controlled basil farm in Morocco, running entirely on its own solar power, shipping chilled basil by road and ferry to European supermarkets. The strategic question for management, investors and supermarket buyers is simple: does generating your own renewable energy and growing indoors in a sunny country offset the cost — environmental and financial — of building that infrastructure and trucking the product a long way to market, compared with the incumbent: soil-grown basil from Kenya, air-freighted to Europe?",
    "answer": "On carbon, yes — decisively. Each kilo of basil on the shelf carries about 2.4 kg CO₂e from Morocco versus 7.0 kg CO₂e from Kenya: roughly a two-thirds lower carbon footprint. The reason is in the stage chart below. Kenya's footprint is dominated by air freight; Morocco trades that for solar-powered growing plus low-carbon sea/road transport. But indoor farming is not a free win — it uses far more land-equivalent (the solar field and building) and more scarce metals (panels, batteries, electronics), so it loses on those measures. Knowing exactly where you win and lose is what lets you price, position and de-risk the venture.",
    "fu_plain": "Every number on this page is measured per 1 kg of basil a shopper actually eats. That is the fair way to compare two farms. But to put 1 kg on the plate you must grow more than 1 kg, because basil is lost along the way — left on the shelf, damaged in transit, trimmed at the packhouse, and the woody stems nobody eats. Adding those losses back, Farm32 has to harvest about 1.33 kg to deliver 1 kg eaten. Every farm that ships further or handles the crop more carries more hidden loss — and pays for it in cost and footprint.",
    "loss_cascade": [
      {
        "step": "Eaten by the consumer",
        "kg": 1.0,
        "note": "The functional unit — what we compare on"
      },
      {
        "step": "+ Retail loss (2.1%)",
        "kg": 1.022,
        "note": "Basil that spoils on the supermarket shelf"
      },
      {
        "step": "+ Distribution loss (12.9%)",
        "kg": 1.173,
        "note": "Damage and spoilage in transit (FAO regional data)"
      },
      {
        "step": "+ Packhouse rejection (2%)",
        "kg": 1.197,
        "note": "Rejected during grading and packing"
      },
      {
        "step": "+ Inedible stems (10%)",
        "kg": 1.33,
        "note": "The woody parts no one eats"
      }
    ],
    "decision_levers": [
      {
        "title": "Where to invest first",
        "body": "The two tallest bars — cultivation energy and distribution — are 88% of Morocco's footprint. Squeezing lighting efficiency, HVAC and route/modal choices moves the number; tinkering with packaging or retail barely registers. Spend effort where the impact (and cost) actually sits."
      },
      {
        "title": "What indoor buys you",
        "body": "Sealed indoor growing means near-zero water use, no pesticides, year-round supply and total control over quality and food safety — strong supermarket selling points. The trade is heavy upfront capital (building, solar, batteries) that shows up as land-equivalent and metals impact."
      },
      {
        "title": "Regulatory & buyer risk",
        "body": "Under CSRD/ESRS, large EU buyers must report supply-chain emissions. A credible, low-carbon, PEFCR-aligned footprint is becoming a condition of getting on the shelf — not a nice-to-have. Air-freighted produce is increasingly a reputational and compliance liability for retailers."
      },
      {
        "title": "Pricing the story",
        "body": "A two-thirds lower carbon footprint, no pesticides and reliable local-to-Europe supply is a premium proposition. The footprint is the evidence base that lets you defend a price and a claim without greenwashing."
      }
    ]
  },
  "archetypes": {
    "indoor": {
      "name": "Indoor farm (Farm32 Morocco CEA)",
      "fu": "1.33 kg basil at consumer",
      "desc": "Sealed-box controlled-environment agriculture: hydroponic basil under LED, CO₂ enrichment, HVAC, PV + battery off-grid power, RO closed-loop water."
    },
    "openfield": {
      "name": "Open field (Kenya reference)",
      "fu": "1.906 kg basil at farm gate",
      "desc": "Soil-grown basil under polytunnel (Naivasha), drip-irrigated with borehole water, diesel-pump backup, split-dose NPK and foliar plant protection."
    }
  }
};
